version: '3.8'

services:

  db:
    image: mysql:8.0.36
    container_name: supermercado-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: supermercado
      MYSQL_USER: appuser
      MYSQL_PASSWORD: apppassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db:/docker-entrypoint-initdb.d
    networks:
      - backend

  adminer:
    image: adminer:latest
    container_name: supermercado-adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge
